version: "3.9"

services:
  api:
    image: reverse-proxy-tv:local
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=rptv
      - POSTGRES_USER=rptv
      - POSTGRES_PASSWORD_FILE=/run/secrets/POSTGRES_PASSWORD
    secrets:
      - POSTGRES_PASSWORD
    depends_on:
      - postgres
    networks:
      - default
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rptv-api.rule=Host(`api.mallepetrus.nl`)"
      - "traefik.http.routers.rptv-api.entrypoints=websecure"
      - "traefik.http.routers.rptv-api.tls.certresolver=myresolver"
      - "traefik.http.services.rptv-api.loadbalancer.server.port=8080"

  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=rptv
      - POSTGRES_USER=rptv
      - POSTGRES_PASSWORD_FILE=/run/secrets/POSTGRES_PASSWORD
    secrets:
      - POSTGRES_PASSWORD
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - default

volumes:
  pg_data:

secrets:
  POSTGRES_PASSWORD:
    file: ./secrets/POSTGRES_PASSWORD.txt

networks:
  traefik:
    external: true
    name: traefik_default
